---
title: "lab5"
author: "Nathanael Reese"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: yes
    toc_float: yes
    theme: darkly
    highlight: zenburn
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Task 1

```{r}
getwd()
```

### Task 2

```{r}
mybin=function(iter=100,n=10, p=0.7){ 
sam.mat=matrix(NA,nr=n,nc=iter, byrow=TRUE)
succ=c()
for( i in 1:iter){
sam.mat[,i]=sample(c(1,0),n,replace=TRUE, prob=c(p,1-p))
succ[i]=sum(sam.mat[,i])
}
succ.tab=table(factor(succ,levels=0:n))
barplot(succ.tab/(iter), col=rainbow(n+1), main="Binomial simulation", xlab="Number of successes")
succ.tab/iter
}
mybin(iter=100,n=10, p=0.7)
mybin(iter=200,n=10, p=0.7)
mybin(iter=500,n=10, p=0.7)
mybin(iter=1000,n=10, p=0.7)
mybin(iter=10000,n=10, p=0.7)

dbin.tab = round(dbinom(0:10, size=10, p = 0.7), 4)
names(dbin.tab) - 0:10
dbin.tab
# Yes theyre close!

```

### Task 3

```{r}
marb.nrep = sample(c(1, 1, 1, 0 ,0),size=5, replace=FALSE,prob=c(3/5, 3/5, 3/5, 2/5, 2/5))
marb.rep = sample(c(1, 1, 1, 0 ,0),size=5, replace=TRUE,prob=c(3/5, 3/5, 3/5, 2/5, 2/5))
marb.nrep
marb.rep

myhyper=function(iter=100,N=20,r=12,n=5){
# make a matrix to hold the samples
#initially filled with NA's
sam.mat=matrix(NA,nr=n,nc=iter, byrow=TRUE)
#Make a vector to hold the number of successes over the trials
succ=c()
for( i in 1:iter){
#Fill each column with a new sample
sam.mat[,i]=sample(rep(c(1,0),c(r,N-r)),n,replace=FALSE)
#Calculate a statistic from the sample (this case it is the sum)
succ[i]=sum(sam.mat[,i])
}
#Make a table of successes
succ.tab=table(factor(succ,levels=0:n))
#Make a barplot of the proportions
barplot(succ.tab/(iter), col=rainbow(n+1), main="HYPERGEOMETRIC simulation", xlab="Number of successes")
succ.tab/iter
}
myhyper(iter=100,n=5, N=20,r=12)
myhyper(iter=200,n=5, N=20,r=12)
myhyper(iter=500,n=5, N=20,r=12)
myhyper(iter=1000,n=5, N=20,r=12)
myhyper(iter=10000,n=5, N=20,r=12)



balltab =round(dhyper(x=0:19, m=12, n=8, k=5), 4)
names(balltab) - 0:5
balltab
# THEYRE CLOSE!
```

### Task 4

```{r}
#i will put the function in here and my comments next to each line of code is what i think it will do
mysample=function(n, iter=10,time=0.5){
for( i in 1:iter){ #iterate the number of times as specified by iter
s=sample(1:10,n,replace=TRUE) #create a sample where we can replace
sf=factor(s,levels=1:10)# encoding sample vector as a factor
barplot(table(sf)/n,beside=TRUE,col=rainbow(10), #plot the factored samples 
main=paste("Example sample()", " iteration ", i, " n= ", n,sep="") ,
ylim=c(0,0.2)
)
Sys.sleep(time)
}
}
mysample(n=1000, iter=30, time=1)
## i see thirty different plots with the probabilities of pulling each number 1-10

```

### Task 5

```{r}
choose(8, 4)
#P(Y > 4), Y~Pois(lambd = 2)
1 - ppois(4, 2)

#P(Y = 10), Y~NegBin(p = 0.4, r = 3)
r = 3
y = 10
n = r
x = y - r

dnbinom(x, n, prob=.4)

# P(Y <= 8), Y~Bin(n = 15, p = 0.4)
pbinom(8, 15, 0.4)

```

### Task 6

```{r}
library(NREESE)
myf(100, 10, .5) #code for the mybin used as a package
#library(ILAS2019)
#ILAS2019::myf()
```
